name: github-repo-stats

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/tutorials-hg2
          databranch: github-repo-stats
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j2:
    name: github-repo-stats-2
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/harfang3d
          databranch: github-repo-stats-harfang3d
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j3:
    name: github-repo-stats-3
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/dogfight-sandbox-hg2
          databranch: github-repo-stats-dogfight-sandbox-hg2
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j4:
    name: github-repo-stats-4
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/harfang-gui
          databranch: github-repo-stats-harfang-gui
          ghtoken: ${{ secrets.ghrs_github_api_token }}

