name: github-repo-stats

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/tutorials-hg2
          databranch: github-repo-stats
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j2:
    name: github-repo-stats-2
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/harfang3d
          databranch: github-repo-stats-harfang3d
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j3:
    name: github-repo-stats-3
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/dogfight-sandbox-hg2
          databranch: github-repo-stats-dogfight-sandbox-hg2
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j4:
    name: github-repo-stats-4
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/harfang-gui
          databranch: github-repo-stats-harfang-gui
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j5:
    name: github-repo-stats-5
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/dogfight-sandbox-hg1
          databranch: github-repo-stats-dogfight-sandbox-hg1
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j6:
    name: github-repo-stats-6
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/harfang-go
          databranch: github-repo-stats-harfang-go
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j7:
    name: github-repo-stats-7
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/python-digital-twin
          databranch: github-repo-stats-/python-digital-twin
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j8:
    name: github-repo-stats-8
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/sample-projects
          databranch: github-repo-stats-/sample-projects
          ghtoken: ${{ secrets.ghrs_github_api_token }}
  j9:
    name: github-repo-stats-9
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: harfang3d/car-simulator
          databranch: github-repo-stats-/car-simulator
          ghtoken: ${{ secrets.ghrs_github_api_token }}
